# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.setEnabled(True)
        Dialog.resize(409, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 96, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 96, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 96, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 96, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        Dialog.setFont(font)
        Dialog.setMouseTracking(False)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setAcceptDrops(False)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.cbInstitution = QtWidgets.QComboBox(Dialog)
        self.cbInstitution.setGeometry(QtCore.QRect(80, 220, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbInstitution.sizePolicy().hasHeightForWidth())
        self.cbInstitution.setSizePolicy(sizePolicy)
        self.cbInstitution.setMaximumSize(QtCore.QSize(241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.cbInstitution.setFont(font)
        self.cbInstitution.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbInstitution.setEditable(False)
        self.cbInstitution.setDuplicatesEnabled(False)
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(100, 30, 191, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTitle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.btnGo = QtWidgets.QPushButton(Dialog)
        self.btnGo.setGeometry(QtCore.QRect(150, 280, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGo.sizePolicy().hasHeightForWidth())
        self.btnGo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnGo.setFont(font)
        self.btnGo.setCheckable(False)
        self.btnGo.setDefault(True)
        self.btnGo.setFlat(False)
        self.btnGo.setObjectName("btnGo")
        self.lblName = QtWidgets.QLineEdit(Dialog)
        self.lblName.setGeometry(QtCore.QRect(80, 170, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.lblName.setFont(font)
        self.lblName.setToolTipDuration(-1)
        self.lblName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lblName.setText("")
        self.lblName.setMaxLength(50)
        self.lblName.setFrame(True)
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lblName.setClearButtonEnabled(True)
        self.lblName.setObjectName("lblName")
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setGeometry(QtCore.QRect(330, 360, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.lblTitle_2 = QtWidgets.QLabel(Dialog)
        self.lblTitle_2.setGeometry(QtCore.QRect(70, 60, 251, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle_2.sizePolicy().hasHeightForWidth())
        self.lblTitle_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblTitle_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle_2.setFont(font)
        self.lblTitle_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTitle_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lblTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle_2.setObjectName("lblTitle_2")
        self.lblTitle_3 = QtWidgets.QLabel(Dialog)
        self.lblTitle_3.setGeometry(QtCore.QRect(10, 110, 391, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle_3.sizePolicy().hasHeightForWidth())
        self.lblTitle_3.setSizePolicy(sizePolicy)
        self.lblTitle_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblTitle_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle_3.setFont(font)
        self.lblTitle_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblTitle_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lblTitle_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle_3.setObjectName("lblTitle_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lblName, self.cbInstitution)
        Dialog.setTabOrder(self.cbInstitution, self.btnGo)
        Dialog.setTabOrder(self.btnGo, self.btnExit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "GPA CALCULATOR"))
        Dialog.setWhatsThis(_translate("Dialog", "This is a GPA Calculator"))
        self.cbInstitution.setToolTip(_translate("Dialog", "Youur Institution"))
        self.cbInstitution.setItemText(0, _translate("Dialog", "Select your Institution"))
        self.cbInstitution.setItemText(1, _translate("Dialog", "Ho Technical University"))
        self.cbInstitution.setItemText(2, _translate("Dialog", "University of Ghana"))
        self.cbInstitution.setItemText(3, _translate("Dialog", "Koforidua Techical University"))
        self.cbInstitution.setItemText(4, _translate("Dialog", "University of Cape Coast"))
        self.lblTitle.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:400;\">GPA | CGPA</span></p></body></html>"))
        self.btnGo.setText(_translate("Dialog", "GO"))
        self.lblName.setToolTip(_translate("Dialog", "Your Name"))
        self.lblName.setPlaceholderText(_translate("Dialog", "Enter Your Name"))
        self.btnExit.setText(_translate("Dialog", "CLOSE"))
        self.lblTitle_2.setText(_translate("Dialog", "<html><head/><body><p>CALCULATOR</p></body></html>"))
        self.lblTitle_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Welcome to your preferred GPA / CGPA Calculator!!!</span></p></body></html>"))

